In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import os
from google.colab import drive
# Load the data
from sklearn.preprocessing import LabelEncoder

In [ ]:
drive.mount('/content/drive/')
working_path="/content/drive/MyDrive/The_Last_MLforBio_ESA/Contest/Q3/dataset.zip (Unzipped Files)"

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:

#/content/drive/MyDrive/The_Last_MLforBio_ESA/Contest/Q3/dataset.zip (Unzipped Files)/train.csv
data = pd.read_csv('/content/drive/MyDrive/The_Last_MLforBio_ESA/Contest/Q3/dataset.zip (Unzipped Files)/train.csv')
labels = pd.read_csv('/content/drive/MyDrive/The_Last_MLforBio_ESA/Contest/Q3/dataset.zip (Unzipped Files)/train_labels.csv')

# Let's assume that the labels are the last column of the labels file
y = labels[labels.columns[-1]].values
encoder = LabelEncoder()
y = encoder.fit_transform(y)

# And all the other columns are our data
X = data[data.columns[1:]].values

# Preprocess the data (Normalization, etc.)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# encoder = LabelEncoder()
# y = encoder.fit_transform(y)
# predictions_labels = encoder.inverse_transform([0,1,4])
# print(predictions_labels)

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Define the network architecture
class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size) 
        self.fc2 = nn.Linear(hidden_size, num_classes)  

    def forward(self, x):
        out = self.fc1(x)
        out = F.relu(out)
        out = self.fc2(out)
        return out

In [ ]:
print(y_train)

[0 0 3 0 4 0 4 2 3 2 0 2 3 2 2 0 0 2 2 0 2 2 1 0 2 1 2 0 1 4 3 0 4 4 1 0 3
 0 1 2 1 3 2 3 0 1 3 2 0 0 4 0 0 2 0 1 3 0 1 4 0 3 4 2 3 0 2 2 3 1 2 0 0 1
 0 3 1 0 1 2 4 3 4 1 2 4 2 0 0 0 2 0 2 2 2 0 2 4 3 0 2 3 2 4 4 3 2 2 0 4 3
 4 2 3 3 4 0 0 0 0 0 4 0 0 2 2 4 3 3 0 3 1 4 0 0 4 0 3 0 3 0 0 2 4 3 0 1 0
 2 4 2 1 4 4 0 0 0 4 0 0 0 0 0 3 0 2 0 0 1 0 3 0 0 0 4 4 3 0 0 0 3 4 3 0 3
 3 0 0 0 0 0 0 2 3 0 1 0 0 1 3 3 0 1 2 1 2 0 4 3 0 0 0 0 0 0 0 0 0 0 4 0 0
 3 3 2 2 0 2 2 3 0 4 0 3 2 0 2 4 0 3 2 4 0 4 0 3 0 0 2 3 0 0 2 0 1 0 4 4 0
 0 3 3 1 0 4 0 1 0 0 2 0 0 0 0 1 0 0 0 0 2 2 3 0 3 0 0 0 3 3 3 1 4 0 3 2 3
 2 4 4 1 0 2 0 2 2 2 3 1 2 2 0 0 2 4 0 3 4 3 4 0 3 0 1 4 4 0 3 0 0 2 0 0 0
 0 0 2 0 0 4 2 4 2 0 2 0 2 0 3 3 3 4 2 2 4 1 1 0 4 2 3 0 1 4 3 2 2 0 2 0 3
 3 1 4 0 4 2 2 0 3 0 2 0 4 0 3 0 3 0 2 4 0 4 2 4 3 0 4 0 0 0 0 1 0 1 2 4 1
 2 3 0 2 1 2 0 2 0 2 0 0 3 3 0 1 1 0 2 0 2 3 4 0 0 1 2 2 4 3 0 2 4 0 0 4 4
 2 4 0 4 0 2 0 3 0 2 0 0 4 4 0 3 2 4 2 0 2 4 0 0 1 3 2 0 2 0 2 0 4 3 3 1 2
 4 0 0 3 1 0 3 1 0 4 1 2 3 0 3 4 4 4 3 3 0 3 2 3 0 1 3 1 0 3 2 4 3 4 4 3 0
 3 0 0 4 2 0 0 2 3 3 0 0 3 2 4 4 2 0 0 1 1 3 4 3 3 0 3 0 0 4 2 0 2 4 0 3 0
 0 0 0 3 0]

In [ ]:
from torch.utils.data import TensorDataset, DataLoader

# Convert to tensors
tensor_x = torch.Tensor(X_train)
tensor_y = torch.Tensor(y_train)
tensor_x_val = torch.Tensor(X_val)
tensor_y_val = torch.Tensor(y_val)

# Create a data loader
train_dataset = TensorDataset(tensor_x, tensor_y)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

# Initialize network
input_size = X.shape[1]
hidden_size = 500
num_classes = len(set(y))
net = MLP(input_size, hidden_size, num_classes)

# Define a Loss function and optimizer
criterion = nn.CrossEntropyLoss()  
optimizer = torch.optim.Adam(net.parameters(), lr=0.001)  

# Train the network
for epoch in range(10): 
    for inputs, labels in train_loader:
        # Zero the parameter gradients
        optimizer.zero_grad()

        # Forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels.long())
        loss.backward()
        optimizer.step()

    # Print statistics
    print('Epoch [%d/%d], Loss: %.4f' % (epoch+1, 10, loss.item()))

Epoch [1/10], Loss: 0.0829
Epoch [2/10], Loss: 0.0033
Epoch [3/10], Loss: 0.0000
Epoch [4/10], Loss: 0.0000
Epoch [5/10], Loss: 0.0000
Epoch [6/10], Loss: 0.0000
Epoch [7/10], Loss: 0.0000
Epoch [8/10], Loss: 0.0000
Epoch [9/10], Loss: 0.0000
Epoch [10/10], Loss: 0.0000

In [ ]:
with torch.no_grad():
    correct = 0
    total = 0
    outputs = net(tensor_x_val)
    _, predicted = torch.max(outputs.data, 1)
    total += tensor_y_val.size(0)
    correct += (predicted == tensor_y_val.long()).sum().item()

print('Validation Accuracy of the model on the test data: {} %'.format(100 * correct / total))

Validation Accuracy of the model on the test data: 99.28571428571429 %

In [ ]:
test_data

,Unnamed: 0,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,sample_661,0.000000,3.395872,3.274023,7.050251,9.895044,0.0,6.898390,0.969307,0.0,...,6.645844,9.276713,10.125284,4.298526,10.140664,10.269407,10.548485,9.958225,8.306577,0.000000
1,sample_72,1.482332,2.907198,4.034365,6.613129,9.456295,0.0,10.038850,0.000000,0.0,...,5.147535,7.685660,10.155552,6.664853,8.469345,12.737940,10.332171,8.624295,8.378936,0.000000
2,sample_9,0.000000,3.642494,4.423558,6.849511,9.464466,0.0,7.947216,0.724214,0.0,...,6.020051,8.712809,10.259096,6.131583,9.923582,11.144295,9.244851,9.484299,4.759151,0.000000
3,sample_316,0.000000,4.365686,4.142609,6.310825,8.623929,0.0,8.268182,1.436801,0.0,...,7.016452,8.868810,10.720501,1.995521,10.332137,11.305788,11.012834,9.786600,4.141212,0.512783
4,sample_519,0.000000,3.981588,4.008218,6.870698,9.477366,0.0,6.972830,0.545771,0.0,...,6.524266,9.411676,10.069087,6.364375,10.120640,11.287528,10.915386,9.641678,5.012032,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,sample_531,0.000000,2.935215,3.494134,7.714294,9.933779,0.0,7.240305,0.597031,0.0,...,5.868237,9.021743,9.476789,2.488926,8.857667,12.202754,9.958519,8.907801,3.788226,0.000000
97,sample_148,0.000000,6.237034,5.043235,6.297397,10.391415,0.0,7.669941,0.913033,0.0,...,5.669299,8.437523,10.524503,1.467801,9.666187,11.258572,10.062033,9.018030,7.737159,0.000000
98,sample_151,0.000000,3.787161,4.216773,7.900879,10.181997,0.0,6.413630,0.366812,0.0,...,5.769801,9.425719,9.987122,1.850279,9.312034,12.098233,10.492925,9.012192,3.438785,0.000000
99,sample_521,0.000000,3.889415,1.903193,6.010008,8.774675,0.0,5.913964,0.000000,0.0,...,7.274690,9.429549,9.525738,5.861908,10.866854,11.066197,10.425709,9.917888,5.201265,0.000000
100,sample_559,0.000000,2.736930,3.005256,6.358199,8.978988,0.0,8.225689,1.639695,0.0,...,6.656396,8.255959,10.476351,3.982921,9.979982,11.819632,10.402042,9.403564,5.191721,0.000000

In [ ]:
# # load the test data
# test_data = pd.read_csv('/content/drive/MyDrive/The_Last_MLforBio_ESA/Contest/Q3/dataset.zip (Unzipped Files)/test.csv')
# test_data = scaler.transform(test_data.values)  # apply the same scaling to the test data
# tensor_test = torch.Tensor(/content/drive/MyDrive/The_Last_MLforBio_ESA/Contest/Q3/dataset.zip (Unzipped Files)/test.csv)

# # Predict with the model
# with torch.no_grad
# load the test data
test_data = pd.read_csv('/content/drive/MyDrive/The_Last_MLforBio_ESA/Contest/Q3/dataset.zip (Unzipped Files)/test.csv')
original_test_data = test_data.copy()  # Keep a copy of original test data

# Extracting features for testing (assuming features are all columns except column 0)
test_features = test_data.iloc[:, 1:]
test_features = scaler.transform(test_features.values)  # apply the same scaling to the test data
tensor_test = torch.Tensor(test_features)

# Predict with the model
with torch.no_grad():
    outputs = net(tensor_test)
    _, predicted = torch.max(outputs.data, 1)

# Decode predictions to original labels
predicted_labels = encoder.inverse_transform(predicted.numpy())

# Create a DataFrame for the answers
answer = pd.DataFrame({
    original_test_data.columns[0]: original_test_data.iloc[:, 0],  # Same as column 0 in test.csv
    'Class': predicted_labels  # Model predictions with original labels
})

# Save to CSV
answer.to_csv('/content/drive/MyDrive/The_Last_MLforBio_ESA/Contest/Q3/dataset.zip (Unzipped Files)/answer.csv', index=False)

In [ ]:
answer

     Unnamed: 0 Class
0    sample_661  PRAD
1     sample_72  BRCA
2      sample_9  PRAD
3    sample_316  KIRC
4    sample_519  PRAD
..          ...   ...
96   sample_531  COAD
97   sample_148  LUAD
98   sample_151  LUAD
99   sample_521  KIRC
100  sample_559  KIRC

[101 rows x 2 columns]