In [34]:
# Import all libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.cluster import SpectralClustering

# Config libraries
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)
sklearn.set_config(transform_output="pandas")

In [35]:
# Read the dataset
cancer_df = pd.read_csv('./data/dataset.csv')
cancer_df_id, cancer_df_data = pd.DataFrame(cancer_df['Unnamed: 0']), cancer_df[cancer_df.columns.difference(['Unnamed: 0'])]
cancer_df_data.iloc[:5, :10]

   gene_0    gene_1   gene_10   gene_100  gene_1000  gene_10000  gene_10001  gene_10002  gene_10003  gene_10004
0     0.0  2.017209  0.591871   9.067588  10.282579    1.598651    8.000563    8.308148    4.877779    7.159912
1     0.0  0.592732  0.000000  11.463070   9.816923    3.962401   10.577674    6.289431    4.158030    6.008637
2     0.0  3.511759  0.000000  11.520388   9.701637    0.000000    1.981122    6.988969    5.851699    7.326951
3     0.0  3.663618  0.000000  10.582518  10.301290    2.175652    6.171159    8.619288    6.574097    6.725646
4     0.0  2.655741  0.000000  10.803849  10.275636    3.068860    7.802846    7.225689    7.888414    7.559339

In [36]:

sp_cancer_clust = SpectralClustering(n_clusters=5, random_state=45, affinity='nearest_neighbors', n_init=5)
sp_cancer_map = sp_cancer_clust.fit_predict(cancer_df_data)


sp_cancer_map

array([2, 3, 2, 2, 0, 2, 1, 2, 0, 2, 0, 1, 2, 0, 0, 0, 3, 1, 1, 2, 0, 1,
       3, 0, 1, 3, 4, 0, 0, 0, 0, 0, 1, 0, 2, 0, 1, 3, 0, 0, 1, 2, 2, 1,
       1, 0, 2, 4, 0, 3, 0, 3, 0, 2, 4, 0, 0, 4, 1, 0, 3, 1, 0, 3, 2, 4,
       0, 2, 1, 0, 1, 0, 0, 3, 0, 3, 0, 1, 2, 4, 0, 2, 0, 0, 2, 2, 0, 0,
       1, 0, 2, 2, 0, 0, 0, 2, 4, 0, 2, 0, 0, 1, 0, 1, 3, 1, 3, 4, 3, 3,
       2, 0, 3, 2, 0, 1, 1, 1, 0, 0, 3, 1, 3, 0, 2, 2, 2, 0, 1, 0, 4, 0,
       4, 0, 0, 1, 3, 0, 1, 4, 0, 2, 0, 1, 3, 4, 2, 0, 3, 3, 3, 3, 0, 0,
       3, 0, 0, 2, 2, 3, 2, 3, 1, 0, 2, 3, 4, 1, 3, 0, 1, 3, 0, 3, 0, 0,
       0, 2, 0, 1, 4, 1, 0, 2, 2, 2, 3, 3, 0, 3, 3, 1, 3, 2, 3, 0, 0, 0,
       3, 3, 0, 1, 1, 1, 1, 2, 0, 2, 0, 3, 3, 0, 2, 0, 2, 0, 0, 0, 3, 0,
       1, 3, 1, 1, 3, 0, 1, 2, 0, 3, 3, 2, 4, 0, 1, 2, 1, 4, 0, 1, 1, 3,
       2, 2, 3, 3, 1, 0, 0, 4, 0, 2, 4, 0, 2, 1, 2, 2, 2, 0, 4, 4, 3, 4,
       4, 2, 3, 0, 0, 1, 1, 0, 4, 2, 1, 2, 0, 0, 1, 0, 0, 0, 0, 3, 3, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 3, 2, 0, 0, 4, 3, 2, 0, 0, 0,
       4, 0, 2, 0, 4, 3, 3, 2, 1, 0, 1, 1, 3, 4, 1, 0, 0, 0, 0, 1, 0, 0,
       2, 0, 1, 0, 3, 2, 1, 0, 2, 4, 0, 0, 0, 3, 3, 3, 0, 0, 2, 3, 0, 1,
       0, 4, 4, 3, 0, 1, 0, 0, 0, 4, 3, 4, 1, 2, 1, 0, 0, 1, 0, 4, 2, 3,
       2, 0, 1, 2, 0, 4, 1, 1, 4, 4, 2, 0, 0, 4, 1, 0, 2, 0, 0, 0, 3, 3,
       1, 3, 0, 1, 4, 2, 0, 3, 2, 0, 0, 0, 3, 0, 0, 2, 0, 2, 4, 0, 3, 0,
       0, 3, 0, 0, 0, 1, 3, 2, 0, 2, 1, 0, 1, 4, 0, 2, 3, 1, 0, 0, 1, 0,
       3, 0, 0, 2, 4, 0, 1, 3, 2, 0, 2, 0, 0, 0, 0, 1, 3, 0, 1, 0, 0, 3,
       3, 1, 4, 2, 4, 0, 1, 1, 0, 2, 1, 4, 3, 3, 0, 2, 2, 0, 2, 3, 1, 2,
       0, 3, 2, 3, 0, 0, 4, 3, 1, 4, 3, 0, 2, 0, 0, 2, 0, 4, 0, 4, 1, 0,
       0, 3, 3, 3, 4, 1, 3, 3, 0, 0, 1, 2, 3, 2, 0, 1, 0, 1, 1, 2, 2, 3,
       0, 1, 4, 4, 0, 1, 1, 0, 0, 2, 1, 4, 0, 0, 4, 3, 0, 0, 0, 1, 2, 3,
       3, 0, 1, 4, 1, 1, 0, 2, 3, 1, 0, 4, 3, 3, 3, 2, 3, 1, 0, 0, 4, 2,
       0, 0, 0, 1, 3, 3, 0, 2, 3, 3, 0, 1, 2, 4, 3, 2, 4, 3, 4, 1, 1, 0,
       0, 1, 1, 4, 0, 3, 2, 2, 1, 0, 3, 0, 0, 4, 0, 2, 2, 0, 0, 4, 0, 1,
       0, 0, 4, 0, 2, 0, 0, 1, 2, 3, 0, 0, 1, 0, 0, 0, 0, 0, 4, 3, 3, 0,
       0, 0, 2, 0, 0, 1, 3, 3, 1, 1, 3, 1, 4, 0, 4, 1, 0, 0, 2, 2, 2, 3,
       2, 2, 4, 0, 0, 4, 3, 1, 0, 1, 4, 0, 0, 0, 2, 3, 1, 0, 2, 1, 2, 0,
       3, 1, 2, 3, 2, 2, 0, 1, 2, 3, 4, 4, 0, 0, 0, 3, 1, 1, 1, 0, 3, 1,
       2, 0, 3, 2, 0, 2, 0, 1, 0, 4, 2, 2, 1, 2, 1, 0, 3, 3, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 2, 4, 1, 0, 0, 1, 0, 3, 0, 0, 2, 0, 2, 0, 4, 0, 0,
       1, 3, 0, 0, 2, 0, 2, 4, 0, 0, 0, 3, 0, 3, 0, 3, 1, 1, 4, 4, 0, 0,
       0, 3, 0, 3, 1, 0, 3, 1, 3, 3, 3, 1, 0, 2, 0, 0, 1, 0, 2, 1, 0, 0,
       0, 0, 2, 3, 0, 3, 4, 2, 2], dtype=int32)

In [37]:
df = pd.DataFrame(sp_cancer_map, columns=['clusters'])
df.to_csv('output.csv', index=False)